tyler-Github/YasifysTools

Dockerfile.amd64, Dockerfile.arm64, docker-compose.yml, package.json
I have added a start script command and a Dockerfile for arm64 and amd64 architectures.
=> Added dockerfiles

.woodpecker.yml, README.md
This has a basic ci pipeline, still need to add auto-deploy to docker but at least it makes sure content is being served.
=> Setup CI pipeline with woodpecker

.woodpecker.yml, README.md, views/404.ejs, views/about.ejs, views/index.ejs, views/player.ejs, views/tiktok.ejs
- [Add ignore_paths to .woodpecker.yml and enable building of docker image for Linux/arm/v7 platform.](https://github.com/tyler-Github/YasifysTools/commit/0d20f07f54697507351be5ce7a24695051a4aed8) 
- [Updated navigation bar with a link to GitHub.](https://github.com/tyler-Github/YasifysTools/commit/158ed6f46fc2f22c1555e899b851f9dab052936a)
=> Updated navbar and pipeline

.woodpecker.yml, app.js, package-lock.json, package.json
This pull request includes several commits by user Codycody31, made on May 22 and May 24, 2023. The changes made are aimed at improving the project's configuration and updating dependencies.
On May 22, the following changes were made:
1. In the `.woodpecker.yml` file, more files and directories were added to the `ignore_path` field, ensuring that they are excluded from the pipeline.
2. The `when` field was added to specific pipeline steps, allowing them to be executed only under certain conditions.
3. The `when` condition was removed from the first pipeline step, modifying the flow of the pipeline.
4. The `yasifys-tools` version in the `package-lock.json` file was updated from 0.8.12 to a newer version.
On May 24, the following changes were made:
1. The `app.js` file was modified to …
=> Update Woodpecker Configuration and Dependencies

app.js, package-lock.json, package.json, views/about.ejs, views/index.ejs, views/player.ejs, views/tiktok.ejs
This pull request introduces a new feature to the navbar brand which includes the version number in all views. Additionally, it improves the semantics of route comments and removes the active class from the Home link in player.ejs and tiktok.ejs and other files.
=> Add version number to navbar and improve semantics and styling

app.js, package-lock.json, package.json
This pull request adds the Semver package to the dependencies in the package.json file to enable semantic versioning. It also includes a new feature in the app.js file that checks for updates from GitHub releases using Semver and logs the results to console.
=> Add Semver Package for Semantic Versioning and Check for GitHub Updates in App.js

app.js
bug fix for fetch not being usable.
=> 🚀 feat(app.js): import node-fetch library to be able to make HTTP requests from the app

package-lock.json, package.json
Meant to fix compatibility issues with other dependencies and other errors.
=> 📦 chore(package.json): downgrade node-fetch package version to 2.6.11

.env.example, .scannerwork/report-task.txt, app.js, package-lock.json, package.json
This pull request includes several updates to improve the app. First, we added .sonar_lock and report-task.txt to the version control for better management of the project's code quality. Then, we added an example environment variable for the app URL and loaded the variables using dotenv to improve the configuration process. Finally, we added comments and functionality to prevent the re-downloading of a video that has already been downloaded. These updates enhance the app's functionality and maintainability.
=> Chore and Feature Updates

.env.example, README.md, app.js, package-lock.json, package.json, routes/index.js, views/404.ejs, views/about.ejs, views/index.ejs, views/player.ejs, views/tiktok.ejs
This pull request introduces several refactoring changes to enhance the project. It adds a constant to store the current version and updates the badges display in the README. The addition of the current version as a constant allows for easier management and access to the version information. Furthermore, the badges displayed in the README are improved for better readability and presentation. Additionally, this pull request includes the addition of the Matomo Tracking Script and a version bump to 0.9.8. These changes aim to optimize the project and improve its functionality.
=> Add current version as a constant, Matomo Tracking, and improve badges display in README

.gitignore, .scannerwork/report-task.txt, .woodpecker.yml, __tests__/handlers.test.js, handlers/index.js, package-lock.json, package.json, routes/index.js, sonar-project.properties
This pull request encompasses multiple changes aimed at enhancing the CI/CD configuration and adding unit tests for handler functions.
The .gitignore file has been updated to include the .scannerwork/ directory, ensuring that Sonar Qube scanner work files are ignored.
A new Sonar Qube configuration file, sonar-project.properties, has been added. This file contains the project key, name, sources, and server URL required for Sonar Qube analysis.
The .woodpecker.yml file has been updated to improve the deployment process for pull requests. This ensures a smoother and more efficient deployment pipeline for pull requests.
The .scannerwork/.sonar_lock and .scannerwork/report-task.txt files have been deleted, removing unnecessary clutter from the repository.
In the handlers.test.js file, unit …
=> Improve CI/CD configuration and add unit tests for handler functions

package-lock.json, package.json
This pull request updates the package version to 1.0.0.
Please review and merge this pull request to finalize the package version update.
=> Update package version to 1.0.0

.eslintrc.js, .woodpecker.yml, __tests__/handlers.test.js, app.js, handlers/index.js, package-lock.json, package.json
This pull request includes multiple updates to enhance the project's code quality and configuration.
The .woodpecker.yml file has been modified to rename the 'Test' stage to 'Install Dependencies'. This change better reflects the purpose of the stage in the pipeline.
ESLint configuration has been added with the introduction of an ESLint configuration file. Additionally, a lint script has been added to the package.json file, ensuring linting checks and code quality standards.
=> Rename stage and add ESLint configuration and refactoring

README.md, __tests__/schemas.test.js, app.js, views/index.ejs, views/tiktok.ejs
This pull request includes various improvements and bug fixes to enhance the codebase and improve user experience. The changes made are as follows:
- Removed an unnecessary console.log statement for the MongoDB connection in the test file.
- Updated the README.md file to remove specific instructions for using social media video downloaders that are not ready.
- Refactored the TikTok page template (tiktok.ejs) to update the placeholder text in the video URL input field to reflect the correct platform.
- Made updates to the app.js file and index.ejs template, including import statement formatting, variable name clarity, view engine sets, code readability improvements, and progress bar functionality enhancements.
- Fixed a typographical error in a comment and improved logging messages in the …
=> Miscellaneous improvements and bug fixes

package-lock.json, package.json
This pull request updates the package.json file to reflect the latest changes and improvements made to the website and associated tools. The version is updated from 1.0.0 to 1.2.0. This version bump signifies the introduction of significant enhancements and improvements to the website and its functionality.
=> Update package version to 1.2.0

.gitignore, __tests__/helpers.test.js, app.js, helpers/helpers.js, package-lock.json, package.json
This pull request includes the following updates:
1. Updated dependencies in the package-lock.json file: 
- Updated engine.io from version 6.4.1 to 6.4.2
- Updated socket.io-parser from version 4.2.2 to 4.2.4
- Updated semver from version 7.5.1 to 7.5.4
2. Added the jest-test-area/ directory to the .gitignore file to exclude test files from version control.
3. Added tests for helper functions in helpers.test.js to ensure their correctness.
4. Added helper functions for file manipulation in the helpers.js file.
5. Added helmet middleware to the app.js file to hide the X-Powered-By header for improved security. The helmet package was also added as a dependency.
6. Added a beforeAll hook in helpers.test.js to create a folder if it doesn't exist before running the tests. Fixed a typo in a …
=> Update dependencies, gitignore, and add helper functions

Dockerfile, README.md, app.js, handlers/index.js, package-lock.json, package.json, views/index.ejs
This pull request introduces several updates:
1. Updated the Node.js version in the Dockerfile to 16.20.1-alpine for better compatibility and security.
2. Added rate limiting to the app.js file to prevent abuse and enhance security. The express-rate-limit package is included as a new dependency in the package.json file.
3. Refactored a console log statement in app.js to use the vLog function for consistency and readability.
4. Fixed various issues in the index.js file: changed single quotes to double quotes for consistency, handled missing or invalid parameters, and improved error handling and logging messages.
5. Updated the download and play button labels in index.ejs to include estimated time.
6. Added support for Google Analytics tracking in index.ejs by including the gtag.js script …
=> Update Node.js version, security improvements, and miscellaneous fixes

views/404.ejs, views/about.ejs, views/index.ejs, views/player.ejs, views/tiktok.ejs
Updated dark/light mode buttons to using icons instead of text to save space.
=> Updated Dark Mode Toggles

views/tiktok.ejs
Fixed some parts of the UI on the tiktok page
=> Add Font Awesome icons and update dark mode toggle button.

__tests__/schemas.test.js, schemas/DownloadExpiration.js
Added the schema and unit tests for it, currently it won't be used, but is planned on being in the future.
=> feat: Add DownloadExpiration schema and tests

.gitignore, .woodpecker.yml, __tests__/handlers.test.js, __tests__/helpers.test.js, app.js, handlers/index.js, helpers/helpers.js
Update to use git describe to get the current version, so we shouldn't have to rely on the package.json version.
=> Update the way the current version is set

.woodpecker.yml, helpers/helpers.js
This commit should fix the way the version number is incorrectly displayed.
=> Update Version Generation and Linting

package-lock.json, package.json, public/sitemap.xml, views/about.ejs, views/player.ejs, views/settings.ejs, views/tiktok.ejs
This pull request includes commits addressing the refactoring of the about.ejs navbar and miscellaneous improvements like updating the package.json version to 1.4.6 and updating URLs, lastmod, and priority values in the sitemap.xml file. These changes aim to enhance functionality and maintainability.
=> Refactor about.ejs navbar and miscellaneous improvements

app.js, package.json
Will fix the following bugs:
- ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' 
- Error: TypeError: Invalid Version: b1b7531
=> Fix bugs in the production version
